#STACK: ci-dotnet-app-stack
#VERSION: 0.0.9

AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  RepositoryName:
    Description: The name of the Ecr Repo
    Type: String
    Default: job-repo
  FullRepositoryId:
    Description: The full repository Id
    Type: String
    Default: ajaykumar011/ci-dotnet-app
  BranchName:
    Description: Branch Name
    Type: String
    Default: develop
  Environment:
    Description: Deploy Environment
    Type: String
    Default: Development
  Prefix:
    Type: String
    Description: The prefix to use for anything deployed with this deployer
    Default: ci
  AppName:
    Type: String
    Description: The prefix to use for anything deployed with this deployer
    Default: dotnet-app
  # ConnectionArn:
  #   Description: Github Connection Arn
  #   Type: String
  #   Default: arn:aws:codestar-connections:ap-south-1:896746609106:connection/4a1d3e76-5345-4c82-9036-3b701b2a5dc6
  ClusterName:
    Description: ECS Container Memory
    Type: String
    Default: taskbased-job
  ContainerMemory:
    Description: ECS Container Memory
    Type: String
    Default: '512'
  ContainerCpu:
    Description: ECS Container CPU
    Type: String
    Default: '256'

Resources:
  CIEcrDeployPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Join [
          "/",
          [
            Fn::ImportValue: TemplatesS3BucketURL,
            "library-system-templates/application-family/content-fetcher/v1_1/ecr-ecs-deploy-pipeline.template",
          ],
        ]
      Parameters:
        Prefix: !Ref Prefix
        AppName: !Ref AppName
        RepositoryName: !Ref RepositoryName
        FullRepositoryId: !Ref FullRepositoryId
        BranchName: !Ref BranchName
        Environment: !Ref Environment
        ClusterName: !Ref ClusterName
        ContainerMemory: !Ref ContainerMemory
        ContainerCpu: !Ref ContainerCpu

Outputs:
  CIEcsRepoArn:
    Value: !GetAtt "CIEcrDeployPipeline.Outputs.EcrRepoArn"
  CIEcrPipelineArn:
    Value: !GetAtt "CIEcrDeployPipeline.Outputs.EcrPipelineArn"

