#STACK: ci-dotnet-app-stack
#VERSION: 0.0.8

AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EcrRepoName:
    Description: The name of the Ecr Repo
    Type: String
    Default: ci-dotnet-app
  FullRepositoryId:
    Description: The full repository Id
    Type: String
    Default: ajaykumar011/ci-dotnet-app
  BranchName:
    Description: Branch Name
    Type: String
    Default: develop
  Environment:
    Description: Deploy Environment
    Type: String
    Default: Development
  PipelineName:
    Description: Name of the Pipeline
    Type: String
    Default: ci-dotnet-app-pipeline

Resources:
  CIEcrDeployPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Join [
          "/",
          [
            Fn::ImportValue: TemplatesS3BucketURL,
            "library-system-templates/application-family/content-fetcher/v1_1/ecr-ecs-deploy-pipeline.template",
          ],
        ]
      Parameters:
        EcrRepoName: !Ref EcrRepoName
        FullRepositoryId: !Ref FullRepositoryId
        BranchName: !Ref BranchName
        Environment: !Ref Environment
        PipelineName: !Ref PipelineName

Outputs:
  CIEcsRepoArn:
    Value: !GetAtt "CIEcrDeployPipeline.Outputs.EcrRepoArn"
  CIEcrPipelineArn:
    Value: !GetAtt "CIEcrDeployPipeline.Outputs.EcrPipelineArn"

